//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cinema
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cinema
    {
        public Cinema()
        {
            this.Hall = new HashSet<Hall>();
            this.Сashier = new HashSet<Сashier>();
        }
    
        public string Adress { get; set; }
        public string Name { get; set; }
        public string City { get; set; }
        public bool Deleted { get; set; }
        public short ID { get; set; }
    
        public virtual ICollection<Hall> Hall { get; set; }
        public virtual ICollection<Сashier> Сashier { get; set; }
    }
}
