//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cinema
{
    using System;
    using System.Collections.Generic;
    
    public partial class Film
    {
        public Film()
        {
            this.Session = new HashSet<Session>();
        }
    
        public string Name { get; set; }
        public string Description { get; set; }
        public short Year { get; set; }
        public System.TimeSpan length { get; set; }
        public string AgeLimit { get; set; }
        public string Producer { get; set; }
        public short ID { get; set; }
        public string Poster { get; set; }
    
        public virtual ICollection<Session> Session { get; set; }
    }
}
