//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cinema
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hall
    {
        public Hall()
        {
            this.Session = new HashSet<Session>();
        }
    
        public byte Num { get; set; }
        public string Type { get; set; }
        public byte AmountOfRow { get; set; }
        public byte AmountOfSeats { get; set; }
        public bool Deleted { get; set; }
        public short ID { get; set; }
    
        public virtual Cinema Cinema { get; set; }
        public virtual ICollection<Session> Session { get; set; }
    }
}
