//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cinema
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hall: IComparable, IEquatable<Hall>
    {
        public Hall()
        {
            this.Session = new HashSet<Session>();
        }
    
        public byte Num { get; set; }
        public string Type { get; set; }
        public byte AmountOfRow { get; set; }
        public byte AmountOfSeats { get; set; }
        public bool Deleted { get; set; }
        public short ID { get; set; }
        public int CompareTo(Object obj)
        {
            Hall x = obj as Hall;
            if (ID > x.ID) return 1;
            else if (ID == x.ID) return 0;
            else return -1;
        }
        public bool Equals(Hall other)
        {
            if (other == null) return false;
            if (ID == other.ID) return true;
            else return false;
        }
        public override int GetHashCode()
        {
            return ID;
        }
        public override bool Equals(Object obj)
        {
            if (obj == null) return false;
            Hall x = obj as Hall;
            if (x == null) return false;
            else return Equals(x);
        }

        public virtual Cinema Cinema { get; set; }
        public virtual ICollection<Session> Session { get; set; }
    }
}
