//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cinema
{
    using System;
    using System.Collections.Generic;
    
    public partial class Session
    {
        public Session()
        {
            this.Seat = new HashSet<Seat>();
        }
    
        public System.DateTime Date { get; set; }
        public short Price { get; set; }
        public System.DateTime Time { get; set; }
        public short ID { get; set; }
    
        public virtual Film Film { get; set; }
        public virtual ICollection<Seat> Seat { get; set; }
        public virtual Hall Hall { get; set; }
    }
}
