//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cinema
{
    using System;
    using System.Collections.Generic;
    
    public partial class Сashier
    {
        public string Login { get; set; }
        public string FIO { get; set; }
        public string Password { get; set; }
        public short ID { get; set; }
    
        public virtual Cinema Cinema { get; set; }
    }
}
